# Generated by Django 3.2.12 on 2023-08-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('budget', models.IntegerField()),
                ('destination_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.destinations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-startDate'],
            },
        ),
        migrations.CreateModel(
            name='Travelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trips')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoUrl', models.CharField(max_length=200)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.destinations')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trips')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', models.CharField(max_length=250)),
                ('complete', models.BooleanField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plannedAct', models.CharField(max_length=250)),
                ('endDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trips')),
            ],
        ),
    ]
