# Generated by Django 4.2.2 on 2023-08-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_trips_destination_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='destination_ids',
        ),
        migrations.AddField(
            model_name='trips',
            name='destination_ids',
            field=models.ManyToManyField(blank=True, to='main_app.destinations'),
        ),
    ]
