# Generated by Django 3.2.12 on 2023-08-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_trips_budget_alter_trips_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='trip_id',
        ),
    ]
