# Generated by Django 3.2.12 on 2023-08-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_photos_trip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photoUrl',
            new_name='url',
        ),
    ]
