# Generated by Django 3.2.12 on 2023-08-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_checklist_trip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='trip_id',
            new_name='trip',
        ),
    ]
