# Generated by Django 3.2.12 on 2023-08-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_trip_id_checklist_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='travelers',
            old_name='trip_id',
            new_name='trip',
        ),
    ]
