# Generated by Django 4.2.4 on 2023-08-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_trips_accepted_users_triprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={},
        ),
        migrations.RemoveField(
            model_name='trips',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='startDate',
        ),
    ]
