# Generated by Django 4.2.2 on 2023-08-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_trips_destination_ids_trips_destination_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
