# Generated by Django 4.2.2 on 2023-08-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_photourl_photos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trips'),
        ),
    ]
